# Generated by Django 2.2.2 on 2022-06-26 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20220625_1348'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='designation',
            field=models.CharField(choices=[('computer', 'computer'), ('chemistry', 'chemistry'), ('physics', 'physics'), ('english', 'english'), ('mathematics', 'mathematics'), ('social sciences', 'social sciences'), ('history', 'history')], default='computer', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='firstname',
            field=models.CharField(default='admin', max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='gender',
            field=models.CharField(default='m', max_length=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='surname',
            field=models.CharField(default='admin', max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teacher',
            name='firstname',
            field=models.CharField(default='admin', max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teacher',
            name='gender',
            field=models.CharField(default='m', max_length=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teacher',
            name='surname',
            field=models.CharField(default='admin', max_length=256),
            preserve_default=False,
        ),
    ]
