# Generated by Django 2.2.2 on 2022-06-26 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20220626_1929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.CharField(choices=[('m', 'male'), ('f', 'female')], max_length=6),
        ),
    ]
